name: Build, scan and push to Docker Hub

on:
  push:
    tags:
      - '*'
    branches:
      - master


jobs:
  run_docker_build_workflow:
    uses: ukwa/ukwa-services/.github/workflows/push-to-docker-hub.yml@master
    with:
      image_name: ukwa/warc-server


